stages:
  - test

java:
  stage: test
  image: openjdk:17
  tags:
    - local
  script:
    - ./gradlew clean test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/test