plugins {
    id 'java'
    id 'application'
}

group = 'ir.ac.kntu'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

application {
    mainClass = 'ir.ac.kntu.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.postgresql:postgresql:42.7.4'
    testRuntimeOnly 'com.h2database:h2:2.2.224'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'net.sourceforge.pmd:pmd-java:6.55.0'
    testImplementation 'com.puppycrawl.tools:checkstyle:10.12.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
    manifest {
        attributes 'Main-Class': 'ir.ac.kntu.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    environment 'JDBC_URL', 'jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1'
    environment 'JDBC_USER', 'sa'
    environment 'JDBC_PASSWORD', ''
}
